<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/Map_Input_Request_req_2.map" md5sum="c48a23b2311af083882f322f853a2473" version="8.0.501" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		Map_Input_Request_req_2.map
*   Map declaration(s):	Map_Input_Request_req_2
*   Input file(s):		smo://smo/name%3Dwsdl-primary/sharedContext%3D%257Bhttp%253A%252F%252FImpl-CCMLibrary%257DCCMSharedBO/message%3D%257Bhttp%253A%252F%252FImpl-CCMLibrary%252FSendCommunicationService%257DSendMessageRequestMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/sharedContext%3D%257Bhttp%253A%252F%252FImpl-CCMLibrary%257DCCMSharedBO/message%3D%257Bhttp%253A%252F%252FImpl-CCMLibrary%252FSendCommunicationService%257DSendMessageRequestMsg/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xltxe="http://www.ibm.com/xmlns/prod/xltxe-j"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:fn="http://www.w3.org/2005/xpath-functions"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io7="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io6="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io9="http://Impl-CCMLibrary/SendCommunicationService"
    xmlns:io8="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io10="wsdl.http://Impl-CCMLibrary/SendCommunicationService"
    xmlns:io="http://www.w3.org/2005/08/addressing"
    xmlns:io3="http://Impl-CCMLibrary"
    xmlns:io2="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io5="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:io4="http://NBDATA"
    xmlns:map="http://Impl-CCM/xslt/Map_Input_Request_req_2"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set fn math map xltxe msl"
    version="2.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io6:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:Map_Input_Request_req_22">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io6:smo" mode="map:Map_Input_Request_req_2">
        </xsl:apply-templates>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io6:smo" to "io6:smo".  -->
  <xsl:template match="io6:smo"  mode="map:Map_Input_Request_req_2">
    <io6:smo>
      <context>
        <shared>
          <xsl:attribute name="xsi:type">
            <xsl:value-of select="'io3:CCMSharedBO'"/>
          </xsl:attribute>
          <!-- a simple data mapping: "body/io9:SendMessage/SendMessageAisInput/io4:loggingDetails/io4:lob"(string) to "lob"(string) -->
          <xsl:if test="body/io9:SendMessage/SendMessageAisInput/io4:loggingDetails/io4:lob">
            <xsl:element name="lob">
              <xsl:value-of select="body/io9:SendMessage/SendMessageAisInput/io4:loggingDetails/io4:lob"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "body/io9:SendMessage/SendMessageAisInput/io4:loggingDetails/io4:applicationNo"(string) to "applicationNumber"(string) -->
          <xsl:if test="body/io9:SendMessage/SendMessageAisInput/io4:loggingDetails/io4:applicationNo">
            <xsl:element name="applicationNumber">
              <xsl:value-of select="body/io9:SendMessage/SendMessageAisInput/io4:loggingDetails/io4:applicationNo"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "body/io9:SendMessage/SendMessageAisInput/io4:loggingDetails/io4:serviceName"(string) to "serviceName"(string) -->
          <xsl:if test="body/io9:SendMessage/SendMessageAisInput/io4:loggingDetails/io4:serviceName">
            <xsl:element name="serviceName">
              <xsl:value-of select="body/io9:SendMessage/SendMessageAisInput/io4:loggingDetails/io4:serviceName"/>
            </xsl:element>
          </xsl:if>
        </shared>
      </context>
      <headers>
        <HTTPHeader>
          <!-- a for-each transform: "io4:headers"(NameValueBO) to "header"(HTTPHeader) -->
          <xsl:apply-templates select="body/io9:SendMessage/SendMessageAisInput/io4:headers" mode="localHeadersToHeader_536873354">
          </xsl:apply-templates>
        </HTTPHeader>
      </headers>
      <body>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'io10:SendMessageRequestMsg'"/>
        </xsl:attribute>
        <io9:SendMessage>
          <!-- a structural mapping: "body/io9:SendMessage/SendMessageAisInput"(SendMessageAIsInput) to "SendMessageAisInput"(SendMessageAIsInput) -->
          <xsl:copy-of select="body/io9:SendMessage/SendMessageAisInput" copy-namespaces="yes"/>
        </io9:SendMessage>
      </body>
    </io6:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io6:smo" to "io6:smo".  -->
  <xsl:template name="map:Map_Input_Request_req_22">
    <xsl:param name="smo"/>
    <context>
      <shared>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'io3:CCMSharedBO'"/>
        </xsl:attribute>
        <!-- a simple data mapping: "$smo/body/io9:SendMessage/SendMessageAisInput/io4:loggingDetails/io4:lob"(string) to "lob"(string) -->
        <xsl:if test="$smo/body/io9:SendMessage/SendMessageAisInput/io4:loggingDetails/io4:lob">
          <xsl:element name="lob">
            <xsl:value-of select="$smo/body/io9:SendMessage/SendMessageAisInput/io4:loggingDetails/io4:lob"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/body/io9:SendMessage/SendMessageAisInput/io4:loggingDetails/io4:applicationNo"(string) to "applicationNumber"(string) -->
        <xsl:if test="$smo/body/io9:SendMessage/SendMessageAisInput/io4:loggingDetails/io4:applicationNo">
          <xsl:element name="applicationNumber">
            <xsl:value-of select="$smo/body/io9:SendMessage/SendMessageAisInput/io4:loggingDetails/io4:applicationNo"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/body/io9:SendMessage/SendMessageAisInput/io4:loggingDetails/io4:serviceName"(string) to "serviceName"(string) -->
        <xsl:if test="$smo/body/io9:SendMessage/SendMessageAisInput/io4:loggingDetails/io4:serviceName">
          <xsl:element name="serviceName">
            <xsl:value-of select="$smo/body/io9:SendMessage/SendMessageAisInput/io4:loggingDetails/io4:serviceName"/>
          </xsl:element>
        </xsl:if>
      </shared>
    </context>
    <headers>
      <HTTPHeader>
        <!-- a for-each transform: "io4:headers"(NameValueBO) to "header"(HTTPHeader) -->
        <xsl:apply-templates select="$smo/body/io9:SendMessage/SendMessageAisInput/io4:headers" mode="localHeadersToHeader_536873354">
        </xsl:apply-templates>
      </HTTPHeader>
    </headers>
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'io10:SendMessageRequestMsg'"/>
      </xsl:attribute>
      <io9:SendMessage>
        <!-- a structural mapping: "$smo/body/io9:SendMessage/SendMessageAisInput"(SendMessageAIsInput) to "SendMessageAisInput"(SendMessageAIsInput) -->
        <xsl:copy-of select="$smo/body/io9:SendMessage/SendMessageAisInput" copy-namespaces="yes"/>
      </io9:SendMessage>
    </body>
  </xsl:template>

  <!-- This rule represents a for-each transform: "io4:headers" to "header".  -->
  <xsl:template match="io4:headers"  mode="localHeadersToHeader_536873354">
    <header>
      <!-- a simple data mapping: "io4:name"(string) to "io8:name"(string) -->
      <io8:name>
        <xsl:value-of select="io4:name"/>
      </io8:name>
      <!-- a simple data mapping: "io4:value"(string) to "io8:value"(string) -->
      <io8:value>
        <xsl:value-of select="io4:value"/>
      </io8:value>
    </header>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::node()[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
