<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/Map_Token_Output_req_1.map" md5sum="6d5fc9a71ee625d61cee47f333213db3" version="8.0.501" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		Map_Token_Output_req_1.map
*   Map declaration(s):	Map_Token_Output_req_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/sharedContext%3D%257Bhttp%253A%252F%252FImpl-CCMLibrary%257DCCMSharedBO/message%3D%257Bhttp%253A%252F%252FImpl-CCMLibrary%252FTokenGeneration%257DGenerateTokenResponseMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/sharedContext%3D%257Bhttp%253A%252F%252FImpl-CCMLibrary%257DCCMSharedBO/message%3D%257Bhttp%253A%252F%252FImpl-CCMLibrary%252FTokenGenerationService%257DGenerateTokenResponseMsg/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xltxe="http://www.ibm.com/xmlns/prod/xltxe-j"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:fn="http://www.w3.org/2005/xpath-functions"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io7="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:in="wsdl.http://Impl-CCMLibrary/TokenGeneration"
    xmlns:io="http://www.w3.org/2005/08/addressing"
    xmlns:io3="http://Impl-CCMLibrary"
    xmlns:in2="http://Impl-CCMLibrary/TokenGeneration"
    xmlns:io2="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io5="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:out2="http://NBDATA"
    xmlns:out3="http://Impl-CCMLibrary/TokenGenerationService"
    xmlns:out="wsdl.http://Impl-CCMLibrary/TokenGenerationService"
    xmlns:map="http://Impl-CCM/xslt/Map_Token_Output_req_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set fn math map xltxe msl"
    version="2.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io5:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:Map_Token_Output_req_12">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io5:smo" mode="map:Map_Token_Output_req_1">
        </xsl:apply-templates>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io5:smo" to "io5:smo".  -->
  <xsl:template match="io5:smo"  mode="map:Map_Token_Output_req_1">
    <io5:smo>
      <body>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'out:GenerateTokenResponseMsg'"/>
        </xsl:attribute>
        <out3:GenerateTokenResponse>
          <!-- variables for custom code -->
          <xsl:variable name="access_token" select="body/in2:GenerateTokenResponse/GenrateTokenOutput/access_token"/>
          <xsl:variable name="failureString" select="context/failInfo/failureString"/>
          <xsl:choose>
            <xsl:when test="fn:boolean($access_token) and $access_token != &apos;&apos;">
              <TokenGenerationAisOutput>
                <out2:response>
                  <!-- a simple mapping with no associated source:  to "out2:status"(string) -->
                  <xsl:element name="out2:status">
                    <xsl:text>200</xsl:text>
                  </xsl:element>
                  <!-- a simple data mapping: "body/in2:GenerateTokenResponse/GenrateTokenOutput/access_token"(string) to "out2:data"(string) -->
                  <xsl:if test="body/in2:GenerateTokenResponse/GenrateTokenOutput/access_token">
                    <xsl:element name="out2:data">
                      <xsl:value-of select="body/in2:GenerateTokenResponse/GenrateTokenOutput/access_token"/>
                    </xsl:element>
                  </xsl:if>
                </out2:response>
              </TokenGenerationAisOutput>
            </xsl:when>
            <xsl:when test="fn:boolean($failureString) and $failureString != &apos;&apos;">
              <TokenGenerationAisOutput>
                <out2:response>
                  <!-- a simple mapping with no associated source:  to "out2:status"(string) -->
                  <xsl:element name="out2:status">
                    <xsl:text>400</xsl:text>
                  </xsl:element>
                  <out2:error>
                    <!-- a simple mapping with no associated source:  to "out2:code"(string) -->
                    <xsl:element name="out2:code">
                      <xsl:text>400</xsl:text>
                    </xsl:element>
                    <!-- a simple mapping with no associated source:  to "out2:message"(string) -->
                    <xsl:element name="out2:message">
                      <xsl:text>Error in Token Generation</xsl:text>
                    </xsl:element>
                  </out2:error>
                </out2:response>
              </TokenGenerationAisOutput>
            </xsl:when>
            <xsl:otherwise>
              <TokenGenerationAisOutput>
                <out2:response>
                  <!-- a simple mapping with no associated source:  to "out2:status"(string) -->
                  <xsl:element name="out2:status">
                    <xsl:text>400</xsl:text>
                  </xsl:element>
                  <out2:error>
                    <!-- a simple mapping with no associated source:  to "out2:code"(string) -->
                    <xsl:element name="out2:code">
                      <xsl:text>400</xsl:text>
                    </xsl:element>
                    <!-- a simple mapping with no associated source:  to "out2:message"(string) -->
                    <xsl:element name="out2:message">
                      <xsl:text>Invalid URL/Parameters</xsl:text>
                    </xsl:element>
                  </out2:error>
                </out2:response>
              </TokenGenerationAisOutput>
            </xsl:otherwise>
          </xsl:choose>
        </out3:GenerateTokenResponse>
      </body>
    </io5:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io5:smo" to "io5:smo".  -->
  <xsl:template name="map:Map_Token_Output_req_12">
    <xsl:param name="smo"/>
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out:GenerateTokenResponseMsg'"/>
      </xsl:attribute>
      <out3:GenerateTokenResponse>
        <!-- variables for custom code -->
        <xsl:variable name="access_token" select="$smo/body/in2:GenerateTokenResponse/GenrateTokenOutput/access_token"/>
        <xsl:variable name="failureString" select="$smo/context/failInfo/failureString"/>
        <xsl:choose>
          <xsl:when test="fn:boolean($access_token) and $access_token != &apos;&apos;">
            <TokenGenerationAisOutput>
              <out2:response>
                <!-- a simple mapping with no associated source:  to "out2:status"(string) -->
                <xsl:element name="out2:status">
                  <xsl:text>200</xsl:text>
                </xsl:element>
                <!-- a simple data mapping: "$smo/body/in2:GenerateTokenResponse/GenrateTokenOutput/access_token"(string) to "out2:data"(string) -->
                <xsl:if test="$smo/body/in2:GenerateTokenResponse/GenrateTokenOutput/access_token">
                  <xsl:element name="out2:data">
                    <xsl:value-of select="$smo/body/in2:GenerateTokenResponse/GenrateTokenOutput/access_token"/>
                  </xsl:element>
                </xsl:if>
              </out2:response>
            </TokenGenerationAisOutput>
          </xsl:when>
          <xsl:when test="fn:boolean($failureString) and $failureString != &apos;&apos;">
            <TokenGenerationAisOutput>
              <out2:response>
                <!-- a simple mapping with no associated source:  to "out2:status"(string) -->
                <xsl:element name="out2:status">
                  <xsl:text>400</xsl:text>
                </xsl:element>
                <out2:error>
                  <!-- a simple mapping with no associated source:  to "out2:code"(string) -->
                  <xsl:element name="out2:code">
                    <xsl:text>400</xsl:text>
                  </xsl:element>
                  <!-- a simple mapping with no associated source:  to "out2:message"(string) -->
                  <xsl:element name="out2:message">
                    <xsl:text>Error in Token Generation</xsl:text>
                  </xsl:element>
                </out2:error>
              </out2:response>
            </TokenGenerationAisOutput>
          </xsl:when>
          <xsl:otherwise>
            <TokenGenerationAisOutput>
              <out2:response>
                <!-- a simple mapping with no associated source:  to "out2:status"(string) -->
                <xsl:element name="out2:status">
                  <xsl:text>400</xsl:text>
                </xsl:element>
                <out2:error>
                  <!-- a simple mapping with no associated source:  to "out2:code"(string) -->
                  <xsl:element name="out2:code">
                    <xsl:text>400</xsl:text>
                  </xsl:element>
                  <!-- a simple mapping with no associated source:  to "out2:message"(string) -->
                  <xsl:element name="out2:message">
                    <xsl:text>Invalid URL/Parameters</xsl:text>
                  </xsl:element>
                </out2:error>
              </out2:response>
            </TokenGenerationAisOutput>
          </xsl:otherwise>
        </xsl:choose>
      </out3:GenerateTokenResponse>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::node()[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
