<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/Map_Send_Email_Success_Response_req_1.map" md5sum="057c19fff1d4e303f7a76c299bcee975" version="8.0.501" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		Map_Send_Email_Success_Response_req_1.map
*   Map declaration(s):	Map_Send_Email_Success_Response_req_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/sharedContext%3D%257Bhttp%253A%252F%252FImpl-CCMLibrary%257DCCMSharedBO/message%3D%257Bhttp%253A%252F%252FImpl-CCMLibrary%252FSendCommunication%257DSendMessageResponseMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/sharedContext%3D%257Bhttp%253A%252F%252FImpl-CCMLibrary%257DCCMSharedBO/message%3D%257Bhttp%253A%252F%252FImpl-AuditLibrary%252FAuditLoggingServices%257DupsertServiceLogRequestMsg/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xltxe="http://www.ibm.com/xmlns/prod/xltxe-j"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:fn="http://www.w3.org/2005/xpath-functions"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io7="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:in="http://Impl-CCMLibrary/SendCommunication"
    xmlns:io="http://www.w3.org/2005/08/addressing"
    xmlns:io3="http://Impl-CCMLibrary"
    xmlns:in2="wsdl.http://Impl-CCMLibrary/SendCommunication"
    xmlns:io2="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io5="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:out2="http://Impl-AuditLibrary/AuditLoggingServices"
    xmlns:out3="http://NBHD"
    xmlns:out="wsdl.http://Impl-AuditLibrary/AuditLoggingServices"
    xmlns:Transform="com.tagic.hnb.Transform"
    xmlns:map="http://Impl-CCM/xslt/Map_Send_Email_Success_Response_req_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set fn math Transform map xltxe msl"
    version="2.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>
  <xltxe:java-extension prefix="Transform" class="com.tagic.hnb.Transform"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io5:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:Map_Send_Email_Success_Response_req_12">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io5:smo" mode="map:Map_Send_Email_Success_Response_req_1">
        </xsl:apply-templates>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io5:smo" to "io5:smo".  -->
  <xsl:template match="io5:smo"  mode="map:Map_Send_Email_Success_Response_req_1">
    <io5:smo>
      <context>
        <!-- a structural mapping: "context/shared"(CCMSharedBO) to "shared"(CCMSharedBO) -->
        <xsl:if test="context/shared">
          <xsl:copy-of select="context/shared" copy-namespaces="yes"/>
        </xsl:if>
      </context>
      <body>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'out:upsertServiceLogRequestMsg'"/>
        </xsl:attribute>
        <out2:upsertServiceLog>
          <serviceLogRequest>
            <!-- a simple data mapping: "context/shared/auditUniqueKey"(string) to "out3:serviceLogId"(string) -->
            <xsl:if test="context/shared/auditUniqueKey">
              <xsl:element name="out3:serviceLogId">
                <xsl:value-of select="context/shared/auditUniqueKey"/>
              </xsl:element>
            </xsl:if>
            <!-- variables for custom code -->
            <xsl:variable name="SendMessageOutput" select="body/in:SendMessageResponse/SendMessageOutput"/>
            <xsl:variable name="message" select="body/in:SendMessageResponse/SendMessageOutput/message"/>
            <xsl:choose>
              <xsl:when test="fn:boolean($message) and $message != &apos;Communication initiated for the requested channels&apos;">
                <!-- a simple data mapping: "body/in:SendMessageResponse/SendMessageOutput"(sendMessageOutputBO) to "out3:errorDetails"(string) -->
                <xsl:element name="out3:errorDetails">
                  <xsl:value-of select="Transform:transformXMLToJSON($SendMessageOutput)"/>
                </xsl:element>
              </xsl:when>
              <xsl:otherwise>
                <!-- a simple data mapping: "body/in:SendMessageResponse/SendMessageOutput"(sendMessageOutputBO) to "out3:response"(string) -->
                <xsl:element name="out3:response">
                  <!-- variables for custom code -->
                  <xsl:variable name="SendMessageOutput1" select="body/in:SendMessageResponse/SendMessageOutput"/>
                  <xsl:value-of select="Transform:transformXMLToJSON($SendMessageOutput1)"/>
                </xsl:element>
              </xsl:otherwise>
            </xsl:choose>
            <!-- a simple data mapping: "context/shared/lob"(string) to "out3:lob"(string) -->
            <xsl:if test="context/shared/lob">
              <xsl:element name="out3:lob">
                <xsl:value-of select="context/shared/lob"/>
              </xsl:element>
            </xsl:if>
          </serviceLogRequest>
        </out2:upsertServiceLog>
      </body>
    </io5:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io5:smo" to "io5:smo".  -->
  <xsl:template name="map:Map_Send_Email_Success_Response_req_12">
    <xsl:param name="smo"/>
    <context>
      <!-- a structural mapping: "$smo/context/shared"(CCMSharedBO) to "shared"(CCMSharedBO) -->
      <xsl:if test="$smo/context/shared">
        <xsl:copy-of select="$smo/context/shared" copy-namespaces="yes"/>
      </xsl:if>
    </context>
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out:upsertServiceLogRequestMsg'"/>
      </xsl:attribute>
      <out2:upsertServiceLog>
        <serviceLogRequest>
          <!-- a simple data mapping: "$smo/context/shared/auditUniqueKey"(string) to "out3:serviceLogId"(string) -->
          <xsl:if test="$smo/context/shared/auditUniqueKey">
            <xsl:element name="out3:serviceLogId">
              <xsl:value-of select="$smo/context/shared/auditUniqueKey"/>
            </xsl:element>
          </xsl:if>
          <!-- variables for custom code -->
          <xsl:variable name="SendMessageOutput" select="$smo/body/in:SendMessageResponse/SendMessageOutput"/>
          <xsl:variable name="message" select="$smo/body/in:SendMessageResponse/SendMessageOutput/message"/>
          <xsl:choose>
            <xsl:when test="fn:boolean($message) and $message != &apos;Communication initiated for the requested channels&apos;">
              <!-- a simple data mapping: "$smo/body/in:SendMessageResponse/SendMessageOutput"(sendMessageOutputBO) to "out3:errorDetails"(string) -->
              <xsl:element name="out3:errorDetails">
                <xsl:value-of select="Transform:transformXMLToJSON($SendMessageOutput)"/>
              </xsl:element>
            </xsl:when>
            <xsl:otherwise>
              <!-- a simple data mapping: "$smo/body/in:SendMessageResponse/SendMessageOutput"(sendMessageOutputBO) to "out3:response"(string) -->
              <xsl:element name="out3:response">
                <!-- variables for custom code -->
                <xsl:variable name="SendMessageOutput1" select="$smo/body/in:SendMessageResponse/SendMessageOutput"/>
                <xsl:value-of select="Transform:transformXMLToJSON($SendMessageOutput1)"/>
              </xsl:element>
            </xsl:otherwise>
          </xsl:choose>
          <!-- a simple data mapping: "$smo/context/shared/lob"(string) to "out3:lob"(string) -->
          <xsl:if test="$smo/context/shared/lob">
            <xsl:element name="out3:lob">
              <xsl:value-of select="$smo/context/shared/lob"/>
            </xsl:element>
          </xsl:if>
        </serviceLogRequest>
      </out2:upsertServiceLog>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::node()[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
