<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/Map_Send_Email_Input_req_1.map" md5sum="3ba8ed434d6d4033452b3c261d0a1190" version="8.0.501" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		Map_Send_Email_Input_req_1.map
*   Map declaration(s):	Map_Send_Email_Input_req_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/sharedContext%3D%257Bhttp%253A%252F%252FImpl-CCMLibrary%257DCCMSharedBO/message%3D%257Bhttp%253A%252F%252FImpl-CCMLibrary%252FSendCommunicationService%257DSendMessageRequestMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/sharedContext%3D%257Bhttp%253A%252F%252FImpl-CCMLibrary%257DCCMSharedBO/message%3D%257Bhttp%253A%252F%252FImpl-CCMLibrary%252FSendCommunication%257DSendMessageRequestMsg/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xltxe="http://www.ibm.com/xmlns/prod/xltxe-j"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:fn="http://www.w3.org/2005/xpath-functions"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io7="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:in="http://NBDATA"
    xmlns:io="http://www.w3.org/2005/08/addressing"
    xmlns:io3="http://Impl-CCMLibrary"
    xmlns:in2="http://Impl-CCMLibrary/SendCommunicationService"
    xmlns:io2="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io5="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:in3="wsdl.http://Impl-CCMLibrary/SendCommunicationService"
    xmlns:out2="wsdl.http://Impl-CCMLibrary/SendCommunication"
    xmlns:out="http://Impl-CCMLibrary/SendCommunication"
    xmlns:map="http://Impl-CCM/xslt/Map_Send_Email_Input_req_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set fn math map xltxe msl"
    version="2.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io5:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:Map_Send_Email_Input_req_12">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io5:smo" mode="map:Map_Send_Email_Input_req_1">
        </xsl:apply-templates>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io5:smo" to "io5:smo".  -->
  <xsl:template match="io5:smo"  mode="map:Map_Send_Email_Input_req_1">
    <io5:smo>
      <context>
        <!-- a structural mapping: "context/shared"(CCMSharedBO) to "shared"(CCMSharedBO) -->
        <xsl:if test="context/shared">
          <xsl:copy-of select="context/shared" copy-namespaces="yes"/>
        </xsl:if>
      </context>
      <headers>
        <HTTPHeader>
          <control>
            <!-- a simple mapping with no associated source:  to "io7:MediaType"(string) -->
            <xsl:element name="io7:MediaType">
              <xsl:text>application/json</xsl:text>
            </xsl:element>
          </control>
          <!-- a for-each transform: "in:headers"(NameValueBO) to "header"(HTTPHeader) -->
          <xsl:apply-templates select="body/in2:SendMessage/SendMessageAisInput/in:headers" mode="localHeadersToHeader_1311558261">
          </xsl:apply-templates>
        </HTTPHeader>
      </headers>
      <body>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'out2:SendMessageRequestMsg'"/>
        </xsl:attribute>
        <out:SendMessage>
          <SendMessageInput>
            <email>
              <!-- a simple data mapping: "body/in2:SendMessage/SendMessageAisInput/in:templateKey"(string) to "templateKey"(string) -->
              <xsl:if test="body/in2:SendMessage/SendMessageAisInput/in:templateKey">
                <xsl:element name="templateKey">
                  <xsl:value-of select="body/in2:SendMessage/SendMessageAisInput/in:templateKey"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "body/in2:SendMessage/SendMessageAisInput/in:email"(string) to "email"(string) -->
              <xsl:if test="body/in2:SendMessage/SendMessageAisInput/in:email">
                <xsl:element name="email">
                  <xsl:value-of select="body/in2:SendMessage/SendMessageAisInput/in:email"/>
                </xsl:element>
              </xsl:if>
            </email>
            <parameter>
              <title>
                <!-- a simple data mapping: "body/in2:SendMessage/SendMessageAisInput/in:caseNo"(string) to "paceidNumber"(string) -->
                <xsl:if test="body/in2:SendMessage/SendMessageAisInput/in:caseNo">
                  <xsl:element name="paceidNumber">
                    <xsl:value-of select="body/in2:SendMessage/SendMessageAisInput/in:caseNo"/>
                  </xsl:element>
                </xsl:if>
              </title>
            </parameter>
          </SendMessageInput>
        </out:SendMessage>
      </body>
    </io5:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io5:smo" to "io5:smo".  -->
  <xsl:template name="map:Map_Send_Email_Input_req_12">
    <xsl:param name="smo"/>
    <context>
      <!-- a structural mapping: "$smo/context/shared"(CCMSharedBO) to "shared"(CCMSharedBO) -->
      <xsl:if test="$smo/context/shared">
        <xsl:copy-of select="$smo/context/shared" copy-namespaces="yes"/>
      </xsl:if>
    </context>
    <headers>
      <HTTPHeader>
        <control>
          <!-- a simple mapping with no associated source:  to "io7:MediaType"(string) -->
          <xsl:element name="io7:MediaType">
            <xsl:text>application/json</xsl:text>
          </xsl:element>
        </control>
        <!-- a for-each transform: "in:headers"(NameValueBO) to "header"(HTTPHeader) -->
        <xsl:apply-templates select="$smo/body/in2:SendMessage/SendMessageAisInput/in:headers" mode="localHeadersToHeader_1311558261">
        </xsl:apply-templates>
      </HTTPHeader>
    </headers>
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out2:SendMessageRequestMsg'"/>
      </xsl:attribute>
      <out:SendMessage>
        <SendMessageInput>
          <email>
            <!-- a simple data mapping: "$smo/body/in2:SendMessage/SendMessageAisInput/in:templateKey"(string) to "templateKey"(string) -->
            <xsl:if test="$smo/body/in2:SendMessage/SendMessageAisInput/in:templateKey">
              <xsl:element name="templateKey">
                <xsl:value-of select="$smo/body/in2:SendMessage/SendMessageAisInput/in:templateKey"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in2:SendMessage/SendMessageAisInput/in:email"(string) to "email"(string) -->
            <xsl:if test="$smo/body/in2:SendMessage/SendMessageAisInput/in:email">
              <xsl:element name="email">
                <xsl:value-of select="$smo/body/in2:SendMessage/SendMessageAisInput/in:email"/>
              </xsl:element>
            </xsl:if>
          </email>
          <parameter>
            <title>
              <!-- a simple data mapping: "$smo/body/in2:SendMessage/SendMessageAisInput/in:caseNo"(string) to "paceidNumber"(string) -->
              <xsl:if test="$smo/body/in2:SendMessage/SendMessageAisInput/in:caseNo">
                <xsl:element name="paceidNumber">
                  <xsl:value-of select="$smo/body/in2:SendMessage/SendMessageAisInput/in:caseNo"/>
                </xsl:element>
              </xsl:if>
            </title>
          </parameter>
        </SendMessageInput>
      </out:SendMessage>
    </body>
  </xsl:template>

  <!-- This rule represents a for-each transform: "in:headers" to "header".  -->
  <xsl:template match="in:headers"  mode="localHeadersToHeader_1311558261">
    <header>
      <!-- a simple data mapping: "in:name"(string) to "io7:name"(string) -->
      <io7:name>
        <xsl:value-of select="in:name"/>
      </io7:name>
      <!-- a simple data mapping: "in:value"(string) to "io7:value"(string) -->
      <io7:value>
        <xsl:value-of select="in:value"/>
      </io7:value>
    </header>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::node()[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
